---
- name: REST API CAC
  hosts: localhost
  vars:
    host: "https://my-client-accelerator-controller-host"
    access_code: "my-access-code"

  tasks:
    - name: get Services from CAC via REST API
      cac_rest_api:
        host: "{{ host }}"
        api_url: "/api/appliance/1.0.0/services"
        access_code: "{{ access_code }}"
      register: result

    - debug: var=result

    - name: get Licenses from CAC via REST API
      cac_rest_api:
        host: "{{ host }}"
        api_url: "/api/appliance/1.0.0/status/license"
        access_code: "{{ access_code }}"
      register: result

    - debug: var=result