FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade 
RUN apt-get install --no-install-recommends -y software-properties-common 
RUN apt-get install --no-install-recommends -y python3-pip build-essential python3-dev 
RUN echo "Etc/UTC" > /etc/timezone
RUN apt-get install --no-install-recommends -y ansible 
RUN apt-get install --no-install-recommends -y python3-paramiko 
RUN apt-get install --no-install-recommends -y sshpass 
RUN apt-get install --no-install-recommends -y ssh 
RUN apt-get install --no-install-recommends -y vim telnet curl iputils-ping 
RUN apt-get install --no-install-recommends -y mysql-client

RUN apt-get install -y git-all
RUN pip install git+https://github.com/riverbed/steelscript 
RUN pip install git+https://github.com/riverbed/steelscript-appresponse
RUN pip3 install mysql-connector-python

#RUN echo "localhost" >> /etc/ansible/hosts

RUN mkdir /usr/lib/python3/dist-packages/ansible/modules/riverbed/
COPY ./modules/service.py /usr/local/lib/python3.8/dist-packages/steelscript/common/
COPY ./modules/create_hostgroup_from_json.py /usr/lib/python3/dist-packages/ansible/modules/riverbed/
COPY ./modules/update_hostgroup_from_json.py /usr/lib/python3/dist-packages/ansible/modules/riverbed/
COPY ./modules/host_group_upload.py /usr/lib/python3/dist-packages/ansible/modules/riverbed/
COPY ./modules/aci_mysql*.py /usr/lib/python3/dist-packages/ansible/modules/riverbed/

WORKDIR /app

CMD ["sleep infinity"]
