---
- name: AppResponse list sources
  hosts: localhost
  connection: local
  vars:
    host: "ip_address_of_AppResponse"
    username: "some_username"
    password: "some_password"

  tasks:
    - name: Get the sources on AppResponse
      list_sources:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: List the sources on the AppResponse
      debug: var=result
